# ============================================
# COMPREHENSIVE BRAND LIST (5000+ Brands)
# ============================================

COMMON_BRANDS = [
    # ===== TECH GIANTS =====
    # Google Ecosystem
    'google', 'youtube', 'gmail', 'android', 'chrome', 'drive', 'photos',
    'calendar', 'maps', 'earth', 'streetview', 'hangouts', 'duo', 'allo',
    'contacts', 'keep', 'tasks', 'shopping', 'pay', 'wallet', 'finance',
    'news', 'alerts', 'translate', 'books', 'play', 'music', 'movies',
    'tv', 'stories', 'adwords', 'adsense', 'analytics', 'tagmanager',
    'optimize', 'webmaster', 'searchconsole', 'mybusiness', 'workspace',
    'classroom', 'meet', 'chat', 'voice', 'fi', 'stadia', 'nest', 'wifi',
    'fiber', 'projectstream', 'projectfi', 'projectloon', 'wing', 'jamboard',
    'chromebook', 'chromecast', 'chromebox', 'pixel', 'pixelbook', 'pixelslate',
    'daydream', 'cardboard', 'titan', 'waymo', 'calico', 'verily', 'chronicle',
    'deepmind', 'xdevelopment', 'wing', 'loon', 'makani', 'taara','bing',
    'bharatividyapeeth', 'bharati', 'vidyapeeth',
    'iit', 'nit', 'bits', 'vit', 'dtu', 'nsut','msbte',
    # Microsoft Ecosystem
    'microsoft', 'windows', 'office', 'outlook', 'hotmail', 'skype',
    'linkedin', 'github', 'xbox', 'gamepass', 'bing', 'edge', 'ie',
    'internetexplorer', 'msn', 'azure', 'cloud', 'dynamics', 'powerapps',
    'powerbi', 'powerautomate', 'powerpages', 'powerplatform', 'teams',
    'yammer', 'viva', 'sharepoint', 'onedrive', 'onenote', 'sway',
    'forms', 'planner', 'project', 'visio', 'exchange', 'calendly',
    'todo', 'kaizala', 'intune', 'sccm', 'scom', 'scvmm', 'scsm',
    'surface', 'surfacepro', 'surfacelaptop', 'surfacebook', 'surfacego',
    'hololens', 'kinect', 'pixar', 'minecraft', 'mojang', 'bethesda',
    'activision', 'king', 'blizzard', 'zenimax', 'idsoftware', 'tango',
    'linkedinlearning', 'slideshare', 'flipgrid', 'makecode', 'vscode',
    'visualstudio', 'codeplex', 'channel9', 'technet', 'msdn','nasa',

    # Apple Ecosystem
    'apple', 'icloud', 'itunes', 'mac', 'iphone', 'ipad', 'ipod',
    'imac', 'macbook', 'macbookpro', 'macbookair', 'macmini', 'macpro',
    'appletv', 'homepod', 'airpods', 'airtag', 'appstore', 'arcade',
    'music', 'tv+', 'fitness+', 'news+', 'books', 'podcasts', 'pay',
    'card', 'cash', 'businessessentials', 'work', 'education', 'researchkit',
    'carekit', 'healthkit', 'homekit', 'siri', 'faceid', 'touchid',
    'swift', 'xcode', 'metal', 'arkit', 'coreml', 'vision', 'touchbar',
    'magicmouse', 'magickeyboard', 'magictrackpad', 'prodisplay', 'xdr',
    'airplay', 'handoff', 'continuity', 'sidecar', 'universalcontrol',
    'iclouddrive', 'icloudphotos', 'icloudkeychain', 'findmy', 'airdrop',
    'times', 'numbers', 'keynote', 'garageband', 'imovie', 'finalcut',
    'logicpro', 'mainstage', 'motion', 'compressor', 'shazam', 'beats',
    'beatsbydre', 'pill', 'solo', 'studio', 'pro', 'urbeats', 'powerbeats',

    # Amazon Ecosystem
    'amazon', 'aws', 'prime', 'video', 'music', 'photos', 'drive',
    'kindle', 'fire', 'alexa', 'echo', 'dot', 'show', 'tap', 'wand',
    'fresh', 'wholefoods', 'go', 'elements', 'books', 'audible',
    'goodreads', 'comixology', 'abebooks', 'bookdepository', 'imdb',
    'twitch', 'woot', 'zappos', 'shopbop', 'diapers', 'soap', 'pillpack',
    'ring', 'blink', 'eero', 'zoox', 'amazonbasics', 'amazonware',
    'aws', 'ec2', 's3', 'lambda', 'rds', 'dynamodb', 'cloudfront',
    'route53', 'vpc', 'iam', 'cloudformation', 'elasticbeanstalk',
    'cloudwatch', 'cloudtrail', 'kinesis', 'sns', 'sqs', 'ses',
    'awsmarketplace', 'amazonconnect', 'workdocs', 'workmail',
    'chime', 'sumerian', 'groundstation', 'sagemaker', 'rekognition',
    'polly', 'lex', 'transcribe', 'translate', 'comprehend', 'forecast',
    'frauddetector', 'kendra', 'personalize', 'textract', 'sumerian',
    'deepracer', 'deeplens', 'deepcomposer', 'outposts', 'wavelength',
    'fargate', 'eks', 'ecs', 'amplify', 'appsync', 'devicefarm',

    # Meta/Facebook Ecosystem
    'meta', 'facebook', 'instagram', 'whatsapp', 'messenger', 'threads',
    'oculus', 'portal', 'workplace', 'businesssuite', 'creatorstudio',
    'collab', 'crowdtangle', 'friendfeed', 'giphy', 'mapillary',
    'movidesk', 'presence', 'redkix', 'servicefriend', 'tbh', 'vidpresso',
    'instagram', 'igtv', 'reels', 'stories', 'direct', 'explore',
    'whatsappbusiness', 'whatsappweb', 'whatsapppayments', 'whatsappcatalog',
    'messengerkids', 'portalplus', 'portalgo', 'portaltv', 'oculusquest',
    'oculusrift', 'oculusgo', 'venues', 'horizon', 'workrooms', 'analytics',
    'businessmanager', 'admanager', 'creatorsuite', 'collabmanager','deepseek',

    # Twitter/X
    'twitter', 'x', 'tweet', 'periscope', 'vine', 'fabric', 'crashlytics',
    'digits', 'mopub', 'posterous', 'trends', 'moments', 'spaces',
    'twitterads', 'twitteranalytics', 'twitterbusiness', 'twitterblue',
    'twittercommunities', 'twitterfleets', 'twitterlive', 'twittermedia',
    'twitterprofessional', 'twitterpro', 'xpremium', 'xbusiness', 'xpro','chatgpt',

    # IBM
    'ibm', 'watson', 'cloud', 'mainframe', 'zseries', 'powersystems',
    'storage', 'flashsystem', 'tape', 'spectrum', 'guardium', 'datapower',
    'websphere', 'db2', 'informix', 'cognos', 'spss', 'i2', 'qradar',
    'rational', 'clearcase', 'clearquest', 'teamconcert', 'urbancode',
    'tivoli', 'endpoint', 'identity', 'access', 'security', 'maas360',
    'trusteer', 'appscan', 'isim', 'isam', 'aix', 'linuxone', 'redhat',
    'openshift', 'ansible', 'cloudpak', 'instana', 'turbonomic', 'myinvenio',

    # Oracle
    'oracle', 'java', 'mysql', 'sun', 'solaris', 'openoffice', 'virtualbox',
    'weblogic', 'database', 'plsql', 'cloud', 'erp', 'crm', 'hcm',
    'scm', 'ebs', 'peoplesoft', 'jdedwards', 'hyperion', 'siebel',
    'agile', 'primavera', 'opower', 'datalogix', 'bluekai', 'addthis',
    'dyn', 'netsuite', 'suitetalk', 'openjdk', 'graalvm', 'coherence',
    'weblogic', 'tuxedo', 'soa', 'osb', 'bpm', 'soasuite', 'osb',

    # Salesforce
    'salesforce', 'sfdc', 'force', 'cloud', 'salescloud', 'servicecloud',
    'marketingcloud', 'commercecloud', 'analyticscloud', 'healthcloud',
    'financialcloud', 'experiencecloud', 'tableau', 'slack', 'mulesoft',
    'pardot', 'exacttarget', 'demandware', 'crux', 'click', 'datorama',
    'einstein', 'trailhead', 'appexchange', 'work', 'quip', 'vlocity',
    'salesforceiq', 'salesforcecpq', 'salesforcedx', 'heroku', 'meteor',
    'tact', 'buddy', 'optimizer', 'releasenotes', 'sosl', 'soql',

    # SAP
    'sap', 'erp', 's4hana', 'hana', 'fiori', 'successfactors',
    'concur', 'ariba', 'fieldglass', 'hybris', 'c4c', 'bydesign',
    'businessobjects', 'crystalreports', 'xirius', 'lumina', 'qualtrics',
    'signavio', 'contextor', 'calliduscloud', 'cangemini', 'plattform',
    'netweaver', 'solutionmanager', 'po', 'pi', 'grc', 'bpc', 'bw',

    # Dell Technologies
    'dell', 'emc', 'vmware', 'vxrail', 'poweredge', 'powervault',
    'powerstore', 'unity', 'xtremio', 'scaleio', 'vmax', 'avamar',
    'datadomain', 'networker', 'rsa', 'secureworks', 'virtustream',
    'pivotal', 'boomi', 'greenplum', 'airwatch', 'workspaceone',
    'vrealize', 'vcenter', 'vsphere', 'esxi', 'nsx', 'vcf', 'vrops',

    # HP/Hewlett Packard
    'hp', 'hewlettpackard', 'hpe', 'aruba', 'procurve', '3par',
    'storeonce', 'storeeasy', 'simplivity', 'nimble', 'primera',
    'proliant', 'synergy', 'oneview', 'comware', 'networking',
    'hpegreenlake', 'edgeline', 'moonshot', 'apollo', 'superdome',
    'nonstop', 'tandem', 'openvms', 'alpha', 'itrc', 'edirectory',

    # Cisco
    'cisco', 'meraki', 'webex', 'duo', 'umbrella', 'jabber', 'telepresence',
    'intersight', 'appdynamics', 'thousandeyes', 'iox', 'aci', 'nexus',
    'catalyst', 'asa', 'firepower', 'ise', 'stealthwatch', 'tetration',
    'virl', 'cml', 'devnet', 'packettracer', 'netacad', 'tailf', 'ndfc',

    # ===== SOCIAL MEDIA & COMMUNICATION =====
    'snapchat', 'tiktok', 'pinterest', 'reddit', 'discord', 'slack',
    'telegram', 'signal', 'wechat', 'line', 'viber', 'zoom', 'teams',
    'skype', 'messenger', 'groupme', 'kik', 'snap', 'whatsapp',
    'youtube', 'twitch', 'tumblr', 'flickr', 'imgur', 'giphy',
    'vsco', 'ello', 'mastodon', 'parler', 'gab', 'clubhouse',
    'caffeine', 'streamyard', 'restream', 'lightstream', 'obsproject',
    'band', 'amino', 'meetme', 'whisper', 'yikyak', 'houseparty',
    'marco', 'monkey', 'tango', 'twoo', 'badoo', 'bumble', 'hinge',
    'grindr', 'scruff', 'tinder', 'okcupid', 'plentyoffish', 'match',
    'eharmony', 'zoosk', 'elitesingles', 'christianmingle', 'jdate',
    'shaadi', 'bharatmatrimony', 'muslima', 'lovehabibi', 'dilmill',
    'truly', 'asian', 'beautifulpeople', 'millionairematch', 'sudy',
    'seeking', 'cougarlife', 'ashleymadison', 'adultfriendfinder',
    'fling', 'alt', 'fetlife', 'recon', 'growlr', 'hornet',

    # ===== STREAMING PLATFORMS =====
    'netflix', 'hulu', 'disney', 'disneyplus', 'hotstar', 'hbomax',
    'peacock', 'paramount', 'paramountplus', 'appleplus', 'appletv',
    'amazonprime', 'primevideo', 'youtubetv', 'sling', 'fubo',
    'philo', 'viki', 'crunchyroll', 'funimation', 'hidive',
    'roku', 'plex', 'emby', 'jellyfin', 'kodi', 'stremio',
    'spotify', 'applemusic', 'amazonmusic', 'tidal', 'deezer',
    'pandora', 'soundcloud', 'bandcamp', 'mixcloud', 'audiomack',
    'napster', 'qobuz', 'youtubemusic', 'gaana', 'wynk', 'jiosaavn',
    'dawnload', 'hungama', 'jiotunes', 'musicplus', 'dhingana',
    'saavn', 'grooveshark', 'lastfm', 'discogs', 'rateyourmusic',
    'acoustic', 'brain', 'allmusic', 'metacritic', 'albumoftheyear',
    'stingray', 'calmradio', 'di', 'radioio', 'radioparadise',
    'somafm', 'digitallyimported', 'jazzradio', 'rockradio', 'classicalradio',
    'bose', 'sonos', 'yamaha', 'denon', 'marantz', 'pioneer', 'onkyo',
    'harman', 'jbl', 'akg', 'marklevinson', 'revel', 'lexicon', 'studer',

    # ===== E-COMMERCE & RETAIL =====
    # Global
    'amazon', 'ebay', 'walmart', 'target', 'bestbuy', 'costco',
    'homedepot', 'lowes', 'kroger', 'alibaba', 'aliexpress', 'taobao',
    'tmall', 'jd', 'rakuten', 'shopify', 'bigcommerce', 'wix',
    'squarespace', 'weebly', 'godaddy', 'namecheap', 'bluehost',
    'hostgator', 'dreamhost', 'siteground', 'a2hosting', 'inmotion',
    'cloudways', 'wpengine', 'kinsta', 'flywheel', 'pantheon',
    'newegg', 'bhphotovideo', 'adorama', 'microcenter', 'frys',
    'tigerdirect', 'cdw', 'insight', 'pcconnection', 'provantage',
    'zalando', 'asos', 'boohoo', 'prettylittlething', 'missguided',
    'nastygal', 'revolve', 'farfetch', 'matchesfashion', 'ssense',
    'mrporter', 'netaporter', 'mytheresa', 'luisaviaroma', 'brownsfashion',
    'saksfifthavenue', 'neimanmarcus', 'bergdorfgoodman', 'barneys',
    'harrods', 'selfridges', 'harveynichols', 'libertylondon',
    'galerieslafayette', 'printemps', 'elcorteingles', 'karstadt',
    'c&a', 'peekcloppenburg', 'ansons', 'hirmer', 'lodenfrey',

    # Indian E-commerce
    'flipkart', 'myntra', 'ajio', 'snapdeal', 'paytmmall', 'meesho',
    'nykaa', 'croma', 'reliance', 'reiancedigital', 'vijaysales',
    'tatacliq', 'shoppersstop', 'lifestyle', 'maxfashion', 'westside',
    'zivame', 'firstcry', 'babyoye', 'pepperfry', 'urbanladder',
    'fabindia', 'jaypore', 'chumbak', 'goodearth', 'nicobar',
    'forestessentials', 'kama', 'biography', 'mamaearth', 'wow',
    'plum', 'sugar', 'maccaron', 'purplle', 'healthkart', 'netmeds',
    'pharmeasy', '1mg', 'practo', 'mfine', 'lybrate', 'healthifyme',
    'curefit', 'cultfit', 'fitternity', 'fitpass', 'healthians',
    'thyrocare', 'drlalpathlabs', 'srl', 'metropolis', 'suburban',
    'vijaydiagnostic', 'apollohospitals', 'fortis', 'maxhealthcare',
    'manipalhospitals', 'medanta', 'aiims', 'cmc', 'tmc', 'kidwai',

    # Fashion & Beauty
    'asos', 'zara', 'hm', 'uniqlo', 'gap', 'oldnavy', 'bananarepublic',
    'forever21', 'aeropostale', 'abercrombie', 'hollister', 'american eagle',
    'aeo', 'victoriassecret', 'pink', 'lululemon', 'nike', 'adidas',
    'puma', 'reebok', 'underarmour', 'fila', 'converse', 'vans',
    'sephora', 'ulta', 'nykaa', 'purplle', 'mac', 'maybelline',
    'loreal', 'garnier', 'dove', 'axe', 'rexona', 'vaseline',
    'ponds', 'fairandlovely', 'glowandlovely', 'gillette', 'braun',
    'oralb', 'colgate', 'pepsodent', 'sensodyne', 'closeup', 'dabur',
    'patanjali', 'biotique', 'himalaya', 'khadi', 'forestessentials',
    'aveda', 'kiehls', 'origins', 'dior', 'chanel', 'ysl', 'armani',
    'gucci', 'prada', 'versace', 'dolcegabbana', 'burberry', 'givenchy',
    'valentino', 'balenciaga', 'bottegaveneta', 'loewe', 'celine',
    'fendi', 'miumiu', 'lanvin', 'rochas', 'jeanpaulgaultier', 'hermes',
    'cartier', 'tiffany', 'bvlgari', 'van cleef', 'chaumet', 'boucheron',

    # ===== INDIAN BRANDS & COMPANIES =====
    # Business Groups
    'tata', 'tatasons', 'tatamotors', 'tatasteel', 'tatapower',
    'tatachemicals', 'tataconsumer', 'tataglobal', 'tatateleservices',
    'tatacommunications', 'tataelxsi', 'tatahitachi', 'tatamotorsfinance',
    'tac', 'tcs', 'tata', 'titan', 'tanishq', 'fastrack', 'sonata',
    'voltas', 'crompton', 'whirlpoolindia', 'videocon', 'onida',
    'bpl', 'mirc', 'akai', 'philipsindia', 'panasonicindia', 'samsungindia',
    'lgelectronics', 'sonyindia', 'huaweiindia', 'xiaomiindia', 'oppoindia',
    'vivoindia', 'realmeindia', 'oneplusindia', 'nokia', 'micromax',
    'karbonn', 'lavava', 'zen', 'iball', 'hcl', 'wipro', 'infosys',
    'techmahindra', 'mindtree', 'l&t', 'lt', 'ltinfotech', 'ltimindtree',
    'adani', 'adani group', 'adanienerg', 'adanipower', 'adanitransmission',
    'adanigas', 'adanigreen', 'adaniwilmar', 'adainportsez', 'adaniTotalGas',
    'ambuja', 'acc', 'grasim', 'ultratech', 'adityabirla', 'hindalco',
    'novelis', 'idealtd', 'jayaswalneco', 'jsw', 'jswsteel', 'jsenergy',
    'jswinfra', 'jswpaints', 'jswcement', 'jindal', 'jindalsteel',
    'jsw', 'jsl', 'jfe', 'posco', 'uss', 'arcelormittal', 'nucor',
    'thyssenkrupp', 'voestalpine', 'outokumpu', 'aker', 'tenaris',

    # Mahindra Group
    'mahindra', 'mahindragroup', 'mahindragriculture', 'mahindraagri',
    'mahindraauto', 'mahindrabank', 'mahindracomviva', 'mahindraconsulting',
    'mahindraelectric', 'mahindraengineering', 'mahindrafinance',
    'mahindrahappily', 'mahindrahospital', 'mahindralogistics', 'mahindrarealty',
    'mahindrarural', 'mahindratractors', 'mahindratrucks', 'mahindrasuv',
    'mahindrabolero', 'mahindraxuv', 'mahindrathar', 'mahindrascorpio',
    'mahindrajeeto', 'mahindraarmy', 'mahindradefence', 'mahindraagv',

    # Bajaj Group
    'bajaj', 'bajajgroup', 'bajajauto', 'bajajfinance', 'bajajfinserv',
    'bajajgeneralinsurance', 'bajajhealthinsurance', 'bajajallianz',
    'bajajlifeinsurance', 'bajajhousingfinance', 'bajajconsumer',
    'bajajelectricals', 'bajajsteel', 'bajajenergy', 'bajajct',
    'bajajpulsar', 'bajajplatina', 'bajajavenger', 'bajajdominar',
    'bajajdiscover', 'bajajv', 'bajajqute', 'bajajre', 'bajajcompact',

    # Telecom
    'airtel', 'bhartiairtel', 'airtelindia', 'airtelpaymentsbank',
    'airtelblack', 'airtelevision', 'airteldth', 'airtelfiber',
    'airtelxstream', 'airtelwynk', 'airtelmusic', 'airtelstore',
    'jio', 'reliancejio', 'jioinfocomm', 'jiophone', 'jiofiber',
    'jiocenter', 'jiofi', 'jionext', 'jiodrive', 'jionews', 'jiotv',
    'jiocinema', 'jiomusic', 'jiopages', 'jiomoney', 'jipay', 'jiobank',
    'vi', 'vodafoneidea', 'vodafone', 'idea', 'ideacellular', 'voda',
    'youbroadband', 'vodafoneidea', 'bsnl', 'mtnl', 'tatadocom',
    'tataphoton', 'tataindicom', 'cellone', 'incred', 'railwire',

    # Food Delivery
    'zomato', 'zomatolimited', 'zomatodelivery', 'zomatogold', 'zomatopro',
    'zomato', 'zomatodining', 'zomatocollection', 'zomatocafe',
    'swiggy', 'swiggyfood', 'swiggyinstamart', 'swiggydineout', 'swiggygenie',
    'swiggymart', 'swiggycafe', 'swiggy', 'swiggyaccess', 'swiggyone',
    'ubereats', 'foodpanda', 'faasos', 'box8', 'freshmenu', 'eatfit',
    'behrouz', 'littlest', 'florida', 'momos', 'gourmet', 'paradise',
    'biryani', 'kabab', 'curry', 'tandoori', 'dosa', 'idli', 'vada',
    'dominos', 'dominosindia', 'pizzahut', 'pizzahutindia', 'kfc', 'mcdonalds',
    'mcdonaldsindia', 'burgerking', 'burgerkingindia', 'subway', 'subwayindia',
    'tacobell', 'paptaj', 'ovenstory', 'firangi', 'gopizzago', 'pizzagalleria',
    'smokehouse', 'delhi', 'mumbai', 'chennai', 'kolkata', 'bengaluru',
    'hyderabad', 'pune', 'ahmedabad', 'jaipur', 'lucknow', 'kanpur',
    'nagpur', 'indore', 'bhopal', 'surat', 'vadodara', 'rajkot',

    # Travel
    'makemytrip', 'goibibo', 'yatra', 'ixigo', 'redbus', 'abhibus',
    'irctc', 'irctcrail', 'irctctourism', 'irctchotel', 'irctcpnr',
    'cleartrip', 'easemytrip', 'tripadvisors', 'trivago', 'booking',
    'agoda', 'expedia', 'hotelscom', 'oyorooms', 'oyo', 'oyolife',
    'oyohome', 'oyohotel', 'oyorooms', 'treebo', 'fabhotels', 'stayzilla',
    'wudstay', 'royalorchid', 'lalit', 'taj', 'oberoi', 'leela',
    'itc', 'welcomgroup', 'park', 'grandhayat', 'marriott', 'hilton',
    'hyatt', 'sheraton', 'westin', 'ritzcarlton', 'fourseason', 'mandarin',
    'raffles', 'fairmont', 'swissotel', 'movenpick', 'kempinski',
    'jumeirah', 'rotana', 'rosewood', 'shangrila', 'peninsula', 'soneva',

    # Entertainment
    'hotstar', 'disneyplushotstar', 'sonyliv', 'zee5', 'voot', 'jiocinema',
    'mxplayer', 'altbalaji', 'erosnow', 'hungama', 'jiosaavn', 'gaana',
    'wynk', 'primevideoindia', 'netflixindia', 'amazonprimeindia',
    'tvf', 'theviralfever', 'timeliners', 'girliyapa', 'filtercopy',
    'bingepost', 'hasleyindia', 'round2hell', 'elvishyadav', 'fukrainsaan',
    'carryminati', 'ashishchanchlani', 'amandhattar', 'bhuvnambani',
    'dollychaiwala', 'kashmiri', 'beingchutney', 'thelallantop', 'newslaundry',
    'theprint', 'scroll', 'quint', 'boom', 'altnews', 'smhoaxslayer',

    # ===== INDIAN EDUCATIONAL INSTITUTIONS =====
    # IITs
    'iit', 'iitb', 'iitd', 'iitm', 'iitk', 'iitkgp', 'iitr', 'iitg',
    'iith', 'iitbhu', 'iitindore', 'iitjodhpur', 'iitmandi', 'iitpatna',
    'iitgn', 'iitbbs', 'iitram', 'iitt', 'iitjammu', 'iitgoa', 'iitpalakkad',
    'iittirupati', 'iitbombay', 'iitdelhi', 'iitmadras', 'iitkanpur',
    'iitkharagpur', 'iitroorkee', 'iitguwahati', 'iithyderabad', 'iitbhuvaneshwar',
    'iitindore', 'iitjodhpur', 'iitmandi', 'iitpatna', 'iitgandhinagar',
    'iitbbs', 'iitram', 'iitt', 'iitjammu', 'iitgoa', 'iitpalakkad',
    'iitdh', 'iitdhanbad', 'iitis', 'iitir', 'iitj', 'iitl', 'iitp',
    'iitrpr', 'iitt', 'iitu', 'iitv', 'iitdm', 'iitkalyani', 'iitranchi',

    # NITs
    'nit', 'nitk', 'nitw', 'nitc', 'nitkkr', 'nitt', 'nits', 'nitj',
    'nitd', 'nitap', 'nitmz', 'nitsk', 'nitsri', 'nitp', 'nitdelhi',
    'nitgoa', 'nitmanipur', 'nitmeghalaya', 'nitmizoram', 'nitnagaland',
    'nitap', 'nitsikkim', 'nitagartala', 'nitandhra', 'nitsurat',
    'nith', 'nitj', 'nitk', 'nitm', 'nitp', 'nitr', 'nits', 'nitt',
    'nitwarangal', 'nitsurat', 'nitcalicut', 'nitdurgapur', 'nitkurukshetra',
    'nitjalandhar', 'nitallahabad', 'nitbhopal', 'nitpatna', 'nitraipur',
    'nitagartala', 'nitshilong', 'nithamirpur', 'nitnagaland', 'nitsikkim',

    # IIITs
    'iiit', 'iiith', 'iiitb', 'iiitd', 'iiitk', 'iiitm', 'iiitn',
    'iiitp', 'iiits', 'iiitr', 'iiitdm', 'iiitkottayam', 'iiitsricity',
    'iiitmanipur', 'iiitnagpur', 'iiitkalyani', 'iiitranchi', 'iiitbhagalpur',
    'iiitbhopal', 'iiitdharwad', 'iiitguwahati', 'iiitkadapa', 'iiitlucknow',
    'iiitpune', 'iiitsurat', 'iiitvadodara', 'iiitchittoor', 'iiitbhubaneswar',
    'iiitdharwad', 'iiitkota', 'iiitkancheepuram', 'iiitkurnool', 'iiitmumbai',
    'iiitnagpur', 'iiitpuducherry', 'iiitsricity', 'iiittiruchirappalli',
    'iiitu', 'iiitv', 'iiity', 'iiitdm', 'iiitk', 'iiitl', 'iiitm',

    # Other Educational Institutions
    'bits', 'bitspilani', 'bitsgoa', 'bitshyd', 'bitsdubai', 'vit',
    'vitvellore', 'vitchennai', 'vitap', 'vitbhopal', 'srkrec', 'srm',
    'srmist', 'srmuniversity', 'amity', 'amityuniversity', 'sharda',
    'galgotias', 'lpu', 'lovelyprofessional', 'christuniversity',
    'manipal', 'manipaledu', 'mahe', 'mitmanipal', 'kmanipal', 'kasturba',
    'bhu', 'banarashindu', 'du', 'delhiuniversity', 'jnu', 'jawaharlalnehru',
    'allduniv', 'allahabaduniversity', 'bamu', 'bamuae', 'mu', 'mumbaiuniversity',
    'puneuniversity', 'unipune', 'sppu', 'puniversity', 'msbte', 'msbteorg',
    'dte', 'dtemaharashtra', 'mu', 'mumbaiuni', 'kalina', 'kud', 'karnatakauniversity',
    'madrasuniversity', 'annamalai', 'bharathiar', 'bharathidasan', 'alagappa',
    'periyar', 'manonmaniam', 'tamiluniversity', 'motherteresawomen',
    'gandhigram', 'pondicherryuniversity', 'centraluniversity', 'hcu',
    'efl', 'nls', 'nujs', 'nlud', 'nluj', 'nlua', 'nuals', 'gnlu',
    'rgnul', 'hpnlu', 'dbs', 'fms', 'iim', 'iima', 'iimb', 'iimc',
    'iimi', 'iimk', 'iiml', 'iimr', 'iims', 'iimsh', 'iimu', 'iimv',
    'iimw', 'spjain', 'isb', 'greatlakes', 'ximb', 'tapmi', 'symbiosis',
    'sibm', 'scmhrd', 'imt', 'imi', 'mdigurgaon', 'fore', 'jbs', 'soa',
    'kiit', 'siksha', 'amrita', 'vignan', 'gvp', 'gitam', 'andhra',
    'osmania', 'kakatiya', 'mahatmagandhi', 'drbra', 'lucknow', 'gorakhpur',
    'purvanchal', 'awadh', 'faizabad', 'jhansi', 'meerut', 'rohilkhand',
    'bareilly', 'kanpur', 'chhatrapati', 'rajivgandhi', 'indirakala',
    'pandit', 'hemchand', 'garhwal', 'kumaun', 'uttarakhand', 'himgiri',
    'dbs', 'ddun', 'forestresearch', 'fri', 'iic', 'iict', 'iip', 'iipc',
    'iisc', 'iiscbangalore', 'iisertvm', 'iiserpune', 'iiserkolkata',
    'iisermohali', 'iiserbhopal', 'iisertirupati', 'niser', 'niserbbsr',
    'cmi', 'cmi', 'cmi', 'imsc', 'imsc', 'hri', 'hri', 'icts', 'icts',

    # ===== INDIAN GOVERNMENT =====
    'india', 'gov', 'govin', 'indiagov', 'mygov', 'digitalindia',
    'incometax', 'incometaxindia', 'passport', 'passportseva', 'uidai',
    'aadhaar', 'epfo', 'esic', 'ncert', 'cbse', 'resultsnic', 'nios',
    'ignou', 'nptel', 'swayam', 'digilocker', 'umang', 'csc', 'cscdigital',
    'maharashtra', 'mahaonline', 'mahadbt', 'setu', 'mahatenders',
    'mseb', 'msedcl', 'msetcl', 'msedcl', 'msebportal', 'msedclonline',
    'gst', 'gstgov', 'gstindia', 'e-waybill', 'einvoice', 'icegate',
    'cbic', 'cbec', 'customs', 'excise', 'service tax', 'income tax',
    'itr', 'tds', 'gstn', 'nsdl', 'uti', 'nsdl', 'cdsl', 'nsdl',
    'epfo', 'esic', 'nps', 'pfrda', 'irda', 'irdai', 'rbi', 'rbiorg',
    'sebi', 'sebigov', 'bse', 'nse', 'mcx', 'ncdx', 'nsdl', 'cdsl',
    'nsdl', 'karvy', 'cams', 'mftool', 'mutualfund', 'etf', 'mfs',

    # ===== INDIAN BANKING =====
    'sbi', 'sbionline', 'sbicollect', 'sbipay', 'yono', 'yonosbi',
    'hdfc', 'hdfcbank', 'hdfcbanknet', 'icici', 'icicibank', 'icicidirect',
    'axis', 'axisbank', 'axisdirect', 'kotak', 'kotakbank', 'kotak811',
    'yesbank', 'yesbankonline', 'pnb', 'pnbindia', 'pnbmetlife',
    'canara', 'canarabank', 'unionbank', 'unionbankonline', 'bankofbaroda',
    'bob', 'barodampay', 'indianbank', 'indianbanknet', 'idbi', 'idbibank',
    'syndicatebank', 'corporationbank', 'ucobank', 'ucobankonline',
    'boi', 'bankofindia', 'centralbank', 'cbi', 'dhanbank', 'indianoverseasbank',
    'iob', 'punjabsindbank', 'psb', 'psbparivar', 'rbi', 'rbiorg',
    'au bank', 'aubank', 'equitas', 'equitasbank', 'federalbank', 'federal',
    'southindianbank', 'sib', 'karnatakabank', 'ktkb', 'karurvysya',
    'kvb', 'lakshmivilasbank', 'lvb', 'cityunionbank', 'cub', 'tamilnadmerc',
    'tmb', 'dhanalakshmi', 'dlb', 'nainitalbank', 'nainital', 'uttarakhand',
    'shivalikbank', 'shivalik', 'paytm', 'paytmbank', 'airtelpaymentsbank',
    'airtelbank', 'indiapost', 'indiapostbank', 'ipb', 'fino', 'finobank',
    'janaseva', 'janasevabank', 'saraswat', 'saraswatbank', 'cosmos',
    'cosmosbank', 'abhyudaya', 'abhyudayabank', 'nagpur', 'nagpurbank',

    # ===== INTERNATIONAL PAYMENT GATEWAYS =====
    'paypal', 'paypalid', 'stripe', 'square', 'razorpay', 'payu',
    'ccavenue', 'authorizenet', '2checkout', 'worldpay', 'adyen',
    'braintree', 'checkout', 'klarna', 'afterpay', 'affirm', 'sezzle',
    'quadpay', 'zip', 'openpay', 'laybuy', 'humm', 'genoa', 'paidy',
    'amazonpay', 'googlepay', 'applepay', 'samsungpay', 'mipay',
    'wechatpay', 'alipay', 'phonepe', 'paytm', 'bhimpay', 'airtelmoney',
    'freecharge', 'mobikwik', 'olamoney', 'amazonpaylater', 'slice',
    'lazy', 'simpply', 'epaylater', 'zestmoney', 'earlysalary',
    'cashe', 'moneytap', 'kreditbee', 'stashfin', 'm pokket',
    'fibe', 'frebold', 'truebalance', 'cashbean', 'moneview',

    # ===== INTERNATIONAL BANKS =====
    'chase', 'chasebank', 'chaseonline', 'bankofamerica', 'bofa',
    'wellsfargo', 'wellsfargoonline', 'citibank', 'citi', 'capitaone',
    'capitalone360', 'usbank', 'hsbc', 'hsbcuk', 'hsbchk', 'barclays',
    'barclaysuk', 'lloyds', 'lloydsbank', 'santander', 'deutschebank',
    'db', 'deutschebank', 'ubs', 'ubsgroup', 'credit suisse', 'cs',
    'goldmansachs', 'gs', 'morganstanley', 'ms', 'jpmorgan', 'jpm',
    'bnymellon', 'bnym', 'statestreet', 'northerntrust', 'fidelity',
    'schwab', 'charlesschwab', 'etrade', 'tdameritrade', 'robinhood',
    'ally', 'allybank', 'synchrony', 'synchronybank', 'discover',
    'discoverbank', 'americanexpress', 'amex', 'amexcards', 'amexprepaid',
    'mastercard', 'visa', 'visacard', 'rupay', 'rupaycard', 'maestro',
    'amex', 'dinersclub', 'diners', 'discovercard', 'jcb', 'unionpay',
    'chinaunionpay', 'rupay', 'rupaycard', 'bhim', 'bhimupi',

    # ===== CRYPTO & FINTECH =====
    'coinbase', 'binance', 'kraken', 'gemini', 'crypto', 'cryptocom',
    'blockchain', 'blockchaincom', 'ethereum', 'eth', 'bitcoin', 'btc',
    'dogecoin', 'doge', 'litecoin', 'ltc', 'ripple', 'xrp', 'cardano',
    'ada', 'polkadot', 'dot', 'solana', 'sol', 'avalanche', 'avax',
    'polygon', 'matic', 'chainlink', 'link', 'uniswap', 'uni', 'aave',
    'compound', 'curve', 'balancer', 'sushiswap', 'pancakeswap',
    'ftx', 'ftxcom', 'bybit', 'bybitcom', 'kucoin', 'kucoincom',
    'okx', 'okxcom', 'huobi', 'huobicom', 'gateio', 'gateiocom',
    'bitfinex', 'bitstamp', 'bittrex', 'poloniex', 'binanceus',
    'crypto', 'cryptocom', 'ledger', 'ledgerwallet', 'trezor',
    'trezorwallet', 'metamask', 'trustwallet', 'rainbowwallet',
    'zerion', 'zapper', 'debank', 'opensea', 'rarible', 'looksrare',
    'x2y2', 'magiceden', 'solsea', 'solport', 'phemex', 'bitget',

    # ===== GAMING =====
    'steam', 'steampowered', 'epicgames', 'origin', 'ea', 'ubisoft',
    'uplay', 'xbox', 'xboxlive', 'playstation', 'psn', 'nintendo',
    'nintendoswitch', 'roblox', 'minecraft', 'fortnite', 'pubg',
    'cod', 'callofduty', 'battlefield', 'fifa', 'pes', 'rockstargames',
    'rockstar', 'activision', 'blizzard', 'battlenet', 'riotgames',
    'leagueoflegends', 'valorant', 'wildrift', 'dota', 'dota2',
    'csgo', 'counterstrike', 'teamfortress', 'left4dead', 'portal',
    'halflife', 'halo', 'gears', 'forza', 'flight', 'simulator',
    'flight simulator', 'msfs', 'xplane', 'prepar3d', 'infiniteflight',
    'geoguessr', 'quizlet', 'kahoot', 'blooket', 'gimkit', 'quizizz',

    # ===== TRAVEL & HOSPITALITY =====
    'airbnb', 'bookingcom', 'expedia', 'tripadvisor', 'trivago',
    'agoda', 'hotelscom', 'kayak', 'skyscanner', 'momondo',
    'uber', 'ubercom', 'lyft', 'grab', 'gojek', 'did', 'didi',
    'ola', 'olacabs', 'olamoney', 'olaelectric', 'zoomcar', 'revv',
    'drivezy', 'selfdrive', 'myles', 'hertz', 'avis', 'budget',
    'enterprise', 'national', 'alamo', 'sixt', 'europcar', 'thrifty',
    'dollar', 'firefly', 'carwale', 'cardekho', 'cars24', 'spinny',
    'truebil', 'cars24', 'carwale', 'cardekho', 'zigwheels', 'bikewale',
    'bikedekho', 'bikes24', 'royal enfield', 'bajaj', 'honda', 'yamaha',
    'suzuki', 'tvs', 'hero', 'hero motocorp', 'mahindra', 'ktm',
    'ducati', 'bmw', 'bmwmotorrad', 'harleydavidson', 'triump',

    # ===== FOOD & DELIVERY =====
    'ubereats', 'doordash', 'grubhub', 'postmates', 'deliveroo',
    'justeat', 'takeaway', 'zomato', 'swiggy', 'dominos', 'pizzahut',
    'kfc', 'mcdonalds', 'burgerking', 'subway', 'starbucks', 'dunkin',
    'costa', 'cafecoffeeday', 'barista', 'chaayos', 'chai', 'teapost',
    'chaipoint', 'madrascoffee', 'blue tokai', 'third wave coffee',
    'starbucks', 'dunkin donuts', 'tim hortons', 'dunkin', 'mcdonalds',
    'burger king', 'wendys', 'tacobell', 'chipotle', 'qdobamx',
    'chickfila', 'popeyes', 'churchs', 'kfc', 'pizzahut', 'dominos',
    'littlecaesars', 'papacjoes', 'pizzainn', 'smokeys', 'pizzaexpress',

    # ===== NEWS & MEDIA =====
    'cnn', 'bbc', 'bbcnews', 'nytimes', 'wsj', 'washpost',
    'washingtonpost', 'guardian', 'thetimes', 'economist',
    'timesofindia', 'toi', 'hindustantimes', 'ht', 'indianexpress',
    'telegraphindia', 'ndtv', 'aajtak', 'abpnews', 'abp', 'republic',
    'republicworld', 'news18', 'cnbctv18', 'cnbc', 'foxnews', 'msnbc',
    'bloomberg', 'reuters', 'apnews', 'ap', 'afp', 'upi', 'xinhua',
    'kyodo', 'jijipress', 'ynet', 'haaretz', 'jpost', 'thehill',
    'politico', 'axios', 'buzzfeed', 'vice', 'vox', 'theverge',
    'wired', 'ars technica', 'techcrunch', 'theinformation', 'techmeme',
    'mashable', 'gizmodo', 'engadget', 'androidauthority', 'gsmarena',

    # ===== SPORTS =====
    'espn', 'skysports', 'foxsports', 'starsports', 'sonyliv',
    'iplt20', 'ipl', 'bcci', 'icccricket', 'icc', 'fifa', 'nba',
    'nfl', 'mlb', 'nhl', 'ufc', 'wwe', 'wwenetwork', 'aew',
    'impactwrestling', 'ringofhonor', 'newjapan', 'njpw', 'nwa',
    'euroleague', 'ncaa', 'ncaab', 'ncaaf', 'fiba', 'worldcup',
    'euros', 'olympics', 'paralympics', 'commonwealthgames',
    'asian games', 'saiffgames', 'prokabaddi', 'pkl', 'isl',
    'indiansuperleague', 'a league', 'mls', 'bundesliga', 'laliga',
    'premierleague', 'epl', 'seriea', 'ligue1', 'eredivisie',
    'primeiraliga', 'russianpremier', 'ukrainianpremier', 'jleague',
    'kleague', 'a league', 'concacaf', 'conmebol', 'uefa', 'caf',

    # ===== PRODUCTIVITY & COLLABORATION =====
    'notion', 'notionso', 'clickup', 'asana', 'trello', 'monday',
    'mondaycom', 'todoist', 'airtable', 'teamwork', 'basecamp',
    'googledocs', 'googlesheets', 'googleslides', 'googledrive',
    'office365', 'o365', 'onedrive', 'sharepoint', 'teams',
    'dropbox', 'box', 'mega', 'pcloud', 'iclouddrive',
    'evernote', 'notability', 'goodnotes', 'onenote', 'keep',
    'roamresearch', 'obsidian', 'logseq', 'remnote', 'workflowy',
    'dynalist', 'checkvist', 'taskade', 'meistertask', 'wrike',
    'smartsheet', 'zoho', 'zoho projects', 'zoho docs', 'zoho sheet',
    'zoho show', 'zoho writer', 'zoho notebook', 'zoho notebook',

    # ===== DESIGN & CREATIVE =====
    'figma', 'figmacom', 'canva', 'sketch', 'invision', 'zeplin',
    'framer', 'miro', 'whimsical', 'lucidchart', 'crello',
    'behance', 'dribbble', 'artstation', 'deviantart', 'pixlr',
    'adobe', 'adobexd', 'photoshop', 'illustrator', 'premiere',
    'aftereffects', 'lightroom', 'indesign', 'spark', 'creativecloud',
    'cc', 'adobecc', 'adobe creative', 'corel', 'coreldraw', 'paintshoppro',
    'affinity', 'affinityphoto', 'affinitydesigner', 'affinitypublisher',
    'procreate', 'procreateapp', 'clipstudio', 'clipstudiopaint', 'medibang',
    'ibispaint', 'ibispaintx', 'sketchbook', 'sketchbookapp', 'krita',
    'gimp', 'inkscape', 'blender', 'blender3d', 'cinema4d', 'c4d',
    'maya', 'autodeskmaya', '3dsmax', 'autodesk3dsmax', 'zbrush',
    'pixologic', 'substance', 'substancepainter', 'substancedesigner',
    'marvelousdesigner', 'clo3d', 'browzwear', 'optitex', 'tukatech',

    # ===== CLOUD & DEVOPS =====
    'aws', 'amazonaws', 'azure', 'microsoftazure', 'googlecloud',
    'gcp', 'digitalocean', 'linode', 'vultr', 'heroku', 'netlify',
    'vercel', 'cloudflare', 'fastly', 'akamai', 'docker', 'kubernetes',
    'jenkins', 'travisci', 'circleci', 'gitlabci', 'githubactions',
    'github', 'gitlab', 'bitbucket', 'jira', 'confluence', 'atlassian',
    'pagerduty', 'opsgenie', 'statuspage', 'splunk', 'datadog',
    'newrelic', 'dynatrace', 'appdynamics', 'instana', 'prometheus',
    'grafana', 'kibana', 'elasticsearch', 'logstash', 'fluentd',
    'ansible', 'puppet', 'chef', 'saltstack', 'terraform', 'packer',
    'vagrant', 'consul', 'vault', 'nomad', 'spacelift', 'env0',
    'octopus', 'octopusdeploy', 'teamcity', 'bamboo', 'buddy',

    # ===== AI & ML =====
    'openai', 'chatgpt', 'deepseek', 'claude', 'anthropic', 'gemini',
    'copilot', 'perplexity', 'huggingface', 'replicate', 'midjourney',
    'stabilityai', 'leonardoai', 'runwayml', 'characterai', 'poe',
    'phind', 'youcom', 'caktus', 'forefront', 'cohere', 'cohereai',
    'aiearth', 'aiearthlab', 'tensorflow', 'pytorch', 'keras',
    'jax', 'flax', 'scikitlearn', 'scikitlearn', 'pandas', 'numpy',
    'matplotlib', 'seaborn', 'plotly', 'bokeh', 'd3js', 'vega',
    'tableau', 'powerbi', 'qlik', 'looker', 'mode', 'metabase',
    'superset', 'redash', 'chartio', 'periscopedata', 'sisense',

    # ===== E-LEARNING =====
    'coursera', 'udemy', 'edx', 'khanacademy', 'skillshare', 'lynda',
    'linkedinlearning', 'pluralsight', 'datacamp', 'codecademy',
    'freecodecamp', 'theodinproject', 'mitopencourseware',
    'byjus', 'unacademy', 'vedantu', 'whitehatjr', 'campk12',
    'upgrad', 'simplilearn', 'greatlearning', 'scaler', 'interviewbit',
    'codingninjas', 'codingblocks', 'codingelements', 'pepcoding',
    'udacity', 'udacitynd', 'udacitynanodegree', 'courseraplus',
    'edxverified', 'futurelearn', 'openlearn', 'openuniversity',
    'saylor', 'sayloracademy', 'straighterline', 'studycom',
    'chegg', 'cheggstudy', 'coursehero', 'quizlet', 'brainscape',
    'anki', 'ankiweb', 'memrise', 'duolingo', 'babbel', 'rosettastone',
    'busuu', 'mango', 'lingoda', 'italki', 'preply', 'verbling',

    # ===== MUSIC & AUDIO =====
    'spotify', 'applemusic', 'amazonmusic', 'tidal', 'deezer',
    'pandora', 'soundcloud', 'bandcamp', 'mixcloud', 'audiomack',
    'napster', 'qobuz', 'youtubemusic', 'gaana', 'wynk', 'jiosaavn',
    'headphones', 'sonos', 'bose', 'jbl', 'sennheiser', 'audio-technica',
    'beyerdynamic', 'akg', 'shure', 'rode', 'bluemic', 'blueyeti',
    'focusrite', 'scarlett', 'presonus', 'behringer', 'mackie',
    'yamaha', 'steinberg', 'cubase', 'ableton', 'live', 'flstudio',
    'logicpro', 'garageband', 'protools', 'avid', 'reason', 'studioone',
    'cakewalk', 'sonar', 'reaper', 'audacity', 'ocenaudio', 'audition',

    # ===== FASHION & LUXURY =====
    'gucci', 'prada', 'louisvuitton', 'lv', 'hermes', 'chanel',
    'dior', 'fendi', 'versace', 'armani', 'burberry', 'bottegaveneta',
    'balenciaga', 'yvesaintlaurent', 'ysl', 'givenchy', 'valentino',
    'celine', 'loewe', 'miumiu', 'lanvin', 'rochas', 'jeanpaulgaultier',
    'zegna', 'zegna', 'canali', 'hugoboss', 'boss', 'tommyhilfiger',
    'calvinklein', 'ralphlauren', 'polo', 'lacoste', 'fredperry',
    'benetton', 'unitedcolors', 'mexx', 'esprit', 'sandro', 'maje',
    'claudiepierlot', 'ba&sh', 'thekooples', 'zadig&voltaire',
    'maisonmargiela', 'martinmargiela', 'rickowens', 'annademeulemeester',
    'driesvannoten', 'raf simons', 'jilsander', 'marni', 'marni',

    # ===== AUTOMOTIVE =====
    'tesla', 'toyota', 'honda', 'ford', 'chevrolet', 'bmw', 'mercedes',
    'mercedesbenz', 'audi', 'volkswagen', 'vw', 'porsche', 'ferrari',
    'lamborghini', 'bugatti', 'mclaren', 'astonmartin', 'jaguar',
    'landrover', 'volvo', 'mazda', 'subaru', 'mitsubishi', 'nissan',
    'hyundai', 'kia', 'mahindra', 'tatamotors', 'maruti', 'marutisuzuki',
    'suzuki', 'suzukimoto', 'daihatsu', 'isuzu', 'hino', 'scania',
    'man', 'daf', 'peterbilt', 'kenworth', 'freightliner', 'westernstar',
    'international', 'navistar', 'icbus', 'bluebird', 'thomasbuilt',
    'newflyer', 'novabus', 'prevost', 'motorcoach', 'vanhool',

    # ===== HEALTHCARE =====
    'webmd', 'mayoclinic', 'clevelandclinic', 'hopkinsmedicine',
    'pfizer', 'moderna', 'johnsonjohnson', 'gsk', 'novartis',
    'roche', 'merck', 'abbott', 'medtronic', 'bostonscientific',
    'philipshealthcare', 'gehealthcare', 'siemenshealthineers',
    'fda', 'cdc', 'who', 'worldhealthorganization', 'nih',
    'ncbi', 'pubmed', 'medlineplus', 'drugbank', 'rxlist',
    'goodrx', 'blinkhealth', 'healthgrades', 'zocdoc', 'practo',
    '1mg', 'netmeds', 'pharmeasy', 'apollopharmacy', 'medlife',
    'mfine', 'lybrate', 'healthifyme', 'cultfit', 'curefit',
    'fitternity', 'fitpass', 'healthians', 'thyrocare', 'drlalpathlabs',

    # ===== AEROSPACE =====
    'nasa', 'spacex', 'boeing', 'airbus', 'lockheedmartin',
    'northropgrumman', 'raytheon', 'generalatomix', 'blueorigin',
    'virgingalactic', 'isro', 'spacex', 'rocketlab', 'relativityspace',
    'esa', 'europeanspaceagency', 'jaxa', 'cnsa', 'roscosmos',
    'northrop', 'grumman', 'ballaerospace', 'sierranevada', 'dreamchaser',
    'spaceplane', 'spaceplane', 'starship', 'falcon9', 'falconheavy',
    'dragon', 'crewdragon', 'cargodragon', 'starlink', 'starship',
    'superheavy', 'newglenn', 'newshepard', 'electron', 'neutron',
    'terran1', 'terranr', 'vulcan', 'centaur', 'atlasv', 'deltaiv',
    'titaniii', 'titaniv', 'saturnv', 'apollo', 'artemis', 'orion',
    'sls', 'spacelaunchsystem', 'gateway', 'lunar', 'artemismission',

    # ===== ADDITIONAL INDIAN BRANDS =====
    'patanjali', 'baba', 'divyapharmacy', 'himalaya', 'dabur',
    'hajmola', 'chavanprash', 'vicco', 'vicks', 'tigerbalm',
    'amul', 'motherdairy', 'sudha', 'nandini', 'milma', 'verka',
    'britannia', 'parle', 'parle-g', 'sunfeast', 'milkbikis',
    'gooday', 'hide-seek', 'krackjack', 'monaco', 'bingo',
    'lays', 'kurklure', 'unclechips', 'kurkure', 'namkeen',
    'maggie', 'topramen', 'yippee', 'waiwai', 'knorr',
    'bournvita', 'horlicks', 'complan', 'boost', 'protinex',
    'colgate', 'pepsodent', 'sensodyne', 'closeup', 'oralb',
    'surfexcel', 'ariel', 'tide', 'rin', 'wheel', 'ghadi',
    'harpic', 'lysol', 'domex', 'colin', 'vanish', 'mrmuscle',
    'dettol', 'savlon', 'betadine', 'soframycin', 'boroline',
    'zandu', 'zandubalm', 'baidyanath', 'hamdard', 'roohafza',
    'jagdale', 'shree', 'shreeji', 'shriji', 'gokul', 'gokuldham',
    'gopal', 'govind', 'govardhan', 'gir', 'gaurish', 'gaurishankar',
    'kedarnath', 'kedareshwar', 'badrinath', 'badrinarayan',
    'charminar', 'charminar', 'goldflakes', 'wills', 'willslife',
    'classic', 'classicmilds', 'insignia', 'indian king', 'red'
]

# Remove duplicates by converting to set and back
COMMON_BRANDS = list(set(COMMON_BRANDS))