# Generated by Django 5.2.5 on 2025-08-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'regusers')], default=1, max_length=50),
        ),
    ]
