# Generated by Django 5.2.5 on 2025-08-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'regusers'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
